Repository fintech4/frontend, pull requests merged in 2024-08, with the labels that each got.

#4 remove: readme.md 삭제 [#1]
  stock-simulator/README.md
  stock-simulator/src/components/StockPriceChart.js
Labels: remove

#15 feat: 주식 차트 컴포넌트
  package-lock.json
  package.json
  public/logo.png
  src/assets/css/styles.css
  src/components/StockPriceChart.js
  src/components/chart/CandleChart.jsx
  src/components/page/MainPage.jsx
  src/stockData/chartData.js
Labels: feat

#13 feat: 종목 정보 검색 스타일링 완료, 로직 구현중
  package-lock.json
  package.json
  src/components/page/MainPage.jsx
  src/components/ui/SearchContainer.jsx
  src/components/ui/StockList.jsx
  src/components/ui/Wallet.jsx
  src/components/ui/bar/StockSearch.jsx
Labels: feat

#23 feat: styling wallet
  package-lock.json
  package.json
  public/images/illustration/money.png
  public/images/illustration/wallet.png
  src/components/page/MainPage.jsx
  src/components/ui/Wallet.jsx
  src/components/ui/bar/Navigation.jsx
  src/components/ui/bar/StockSearch.jsx
Labels: feat

#27 feat: 매수매도 컴포넌트 구현, 우측하단 로고 삽입
  public/images/logo/bg_logo.png
  public/logo.png
  src/assets/css/styles.css
  src/components/page/MainPage.jsx
  src/components/ui/OrderForm.jsx
  src/components/ui/Wallet.jsx
  src/components/ui/bar/Navigation.jsx
  src/components/ui/bar/StockSearch.jsx
Labels: feat

#29 feat: 마이페이지 스타일링 + 통신 빈 코드 구현
  package-lock.json
  package.json
  src/components/page/MainPage.jsx
  src/components/page/MyPage.jsx
  src/components/ui/MyTable.jsx
  src/components/ui/StockTable.jsx
Labels: feat

#28 feat[#22] 달력에서 날짜 선택에 따른 차트 변화 구현
  .vscode/launch.json
  package-lock.json
  package.json
  src/components/chart/CandleChart.jsx
  src/components/ui/Calendar.jsx
  src/components/ui/ChartComponent.jsx
Labels: feat

#33 feat: axios 코드 작성 완료 (MyPage)
  src/components/page/MyPage.jsx
  src/components/ui/tables/MyTable.jsx
  src/components/ui/tables/StockTable.jsx
Labels: feat

#36 feat[#35]: 리다이렉션 규칙 정의
  netlify.toml
Labels: feat

#43 fix: API호출 실패 방어코드 추가(MyPage)
  src/components/page/MyPage.jsx
Labels: fix

#56 feat: 모델 생성 [#52]
  src/App.jsx
  src/models/AccountAssets.js
  src/models/AccountUsers.js
  src/models/Holdings.js
  src/models/Stocks.js
  src/models/StocksHistory.js
  src/setupProxy.js
Labels: feat

#75 feat: 주식 종목 검색, 정보, 차트 상태관리
  src/components/chart/CandleChart.jsx
  src/components/page/MainPage.jsx
  src/components/ui/SearchContainer.jsx
  src/components/ui/bar/StockSearch.jsx
  src/context/stocksContext.js
  src/models/Stocks.js
  src/models/StocksHistory.js
  src/setupProxy.js
  src/stockData/chartData.js
Labels: feat

#79 Feat[#13] 매수,매도 기능
  src/components/page/MainPage.jsx
  src/components/ui/OrderForm.jsx
  src/components/ui/SearchContainer.jsx
  src/components/ui/Wallet.jsx
  src/context/stocksContext.js
  src/models/AccountAssets.js
  src/setupProxy.js
Labels: feat

#84 feat[#17] Context API 적용 완료
  src/components/ui/ChartComponent.jsx
  src/components/ui/OrderForm.jsx
  src/components/ui/Wallet.jsx
  src/components/ui/chart/CandleChart.jsx
  src/context/stocksContext.js
  src/stockData/chartData.js
Labels: feat

#89 style: 컴포넌트 편집 [#85]
  src/components/page/MyPage.jsx
  src/components/ui/Calendar.jsx
  src/components/ui/OrderForm.jsx
  src/components/ui/SearchContainer.jsx
  src/components/ui/Wallet.jsx
  src/components/ui/tables/MyTable.jsx
  src/components/ui/tables/StockTable.jsx
  src/context/stocksContext.js
Labels: feat

#94 feat: 파비콘, 타이틀 변경 [#93]
  public/images/favicon1.png
  public/images/favicon2.png
  public/index.html
  src/components/ui/ChartComponent.jsx
Labels: feat

#95 fix: 파비콘 설정 오류 수정 [#93]
  public/index.html
Labels: feat

#96 fix: 파비콘 설정 오류 수정 [#96]
  public/index.html
Labels: fix

#97 fix: 종목 검색 관련 타이포 수정 [#97]
  src/components/ui/SearchContainer.jsx
Labels: fix

#98 fix: 종목 검색, 달력 선택창 간격 조정 [#98]
  src/components/ui/Calendar.jsx
  src/components/ui/SearchContainer.jsx
Labels: feat

#99 style: css 간격 조정(네비게이션바, 종목 검색) [#99]
  src/components/ui/SearchContainer.jsx
  src/components/ui/StockList.jsx
  src/components/ui/bar/Navigation.jsx
Labels: style
